MvcPersonajesSeries/Models/ErrorViewModel.cs
namespace MvcPersonajesSeries.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcPersonajesSeries/Models/Personaje.cs
namespace MvcPersonajesSeries.Models
{
    public class Personaje
    {
        public int IdPersonaje { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public string Serie { get; set; }
    }
}

MvcPersonajesSeries/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPersonajesSeries.Models;
using System.Diagnostics;

namespace MvcPersonajesSeries.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcPersonajesSeries/Controllers/PersonajesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPersonajesSeries.Models;
using MvcPersonajesSeries.Services;

namespace MvcPersonajesSeries.Controllers
{
    public class PersonajesController : Controller
    {
        private ServiceAPIPersonajes service;

        public PersonajesController(ServiceAPIPersonajes service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Personaje> personajes = await this.service.GetPersonajesAsync();
            return View(personajes);
        }

        public async Task<IActionResult> BuscadorSerie()
        {
            List<string> series = await this.service.GetSeriesAsync();
            ViewData["SERIES"] = series;
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Personaje personaje)
        {
            await this.service.CreatePersonajeAsync(personaje);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int idpersonaje)
        {
            Personaje personaje = await this.service.FindPersonajeAsync(idpersonaje);
            return View(personaje);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Personaje personaje)
        {
            await this.service.UpdatePersonajeAsync(personaje);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int idpersonaje)
        {
            await this.service.DeletePersonajeAsync(idpersonaje);
            return RedirectToAction("Index");
        }
    }
}

MvcPersonajesSeries/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcPersonajesSeries/Views/Personajes/BuscadorSerie.cshtml
@{
    ViewData["Title"] = "BuscadorSerie";
    List<string> series = ViewData["SERIES"] as List<string>;
}

<h1>BuscadorSerie</h1>
<p>
    <a asp-action="Index">Back to Index</a>
</p>
<form method="post">
    <label class="form-label">Serie</label>
    <select class="form-select" name="serie">
    </select>
    <button id="buttonserie" type="button" class="btn btn-info mt-3">
        Buscar personajes
    </button>
</form>

<table id="tablepersonajes" class="table-borderless table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Imagen</th>
            <th>Serie</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@section Scripts {
    <script>
        $(function () {
            let urlApi = "https://apipersonajesseries2024alejo.azurewebsites.net/";
            let request = "api/Personajes/Series";

            $.ajax({
                url: urlApi + request,
                method: "GET",
                success: function (data) {
                    let html = "";
                    $.each(data, function (index, serie) {
                        html += "<option value='" + serie + "'>" + serie + "</option>";
                    });
                    $("select").html(html);
                }
            });

            $("#buttonserie").on("click", function () {
                let serie = $("select").find(":selected").val();
                let request = "api/Personajes/PersonajesSeries/" + serie;
                $.ajax({
                    url: urlApi + request,
                    method: "GET",
                    success: function (data) {
                        let html = "";
                        $.each(data, function (index, personaje) {
                            html += "<tr>";
                            html += "<td>" + personaje.idPersonaje + "</td>";
                            html += "<td>" + personaje.nombre + "</td>";
                            html += "<td><img width='200' height='200' src='" + personaje.imagen + "' /></td>";
                            html += "<td>" + personaje.serie + "</td>";
                            html += "</tr>";
                        });
                        $("#tablepersonajes tbody").html(html);
                    }
                });
            });
        });
    </script>
}

MvcPersonajesSeries/Views/Personajes/Create.cshtml
@model MvcPersonajesSeries.Models.Personaje

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="idpersonaje" value="0" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Serie" class="control-label"></label>
                <input asp-for="Serie" class="form-control" />
                <span asp-validation-for="Serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MvcPersonajesSeries/Views/Personajes/Index.cshtml
@model IEnumerable<MvcPersonajesSeries.Models.Personaje>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create"
       class="btn btn-success mt-3">
        Crear Personaje
    </a>
    <a asp-action="BuscadorSerie"
       class="btn btn-info mt-3">
        Buscar por Serie
    </a>
</p>
<table class="table-borderless table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Imagen</th>
            <th>Serie</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.IdPersonaje</td>
                <td>@item.Nombre</td>
                <td>
                    <img width="200" height="200" src="@item.Imagen" />
                </td>
                <td>@item.Serie</td>
                <td>
                    <a asp-controller="Personajes"
                       asp-action="Update"
                       asp-route-idpersonaje="@item.IdPersonaje"
                       class="btn btn-warning btn-sm">
                        Update
                    </a>
                    <a asp-controller="Personajes"
                       asp-action="Delete"
                       asp-route-idpersonaje="@item.IdPersonaje"
                       class="btn btn-danger btn-sm">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

MvcPersonajesSeries/Views/Personajes/Update.cshtml
@model MvcPersonajesSeries.Models.Personaje

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="idpersonaje" value="@Model.IdPersonaje" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Serie" class="control-label"></label>
                <input asp-for="Serie" class="form-control" />
                <span asp-validation-for="Serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MvcPersonajesSeries/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcPersonajesSeries</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcPersonajesSeries.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcPersonajesSeries</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse d-sm-inline-flex justify-content-between collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Personajes"
                               asp-action="Index">
                                Personajes
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcPersonajesSeries - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>